const tintColorLight = '#2B4FA7'; // Blue for light mode
const tintColorDark = '#001A3D'; // Very dark blue for dark mode

export const Colors = {
  light: {
    text: '#1A202C',
    textPrimary: '#1A202C',
    textSecondary: '#4A5568',
    background: '#F7FAFC',
    backgroundSecondary: '#747485',
    tint: tintColorLight,
    icon: '#4A5568',
    tabIconDefault: '#718096',
    tabIconSelected: tintColorLight,
    buttonText: '#1A202C',
    framButtonText: '#FFFFFF',
    buttonBackground: '#E2E8F0',
    buttonSecondary: '#CBD5E0',
    inactiveButtonColor: '#CBD5E0',
    inputBackground: '#E2E8F0',
    inputText: '#1A202C',
    messageBackground: '#FFFFFF',
    messageText: '#1A202C',
    messageTimestamp: '#718096',
    notificationBackground: '#CBD5E0',
    notificationText: '#1A202C',
    transparent: 'rgba(255, 255, 255, 0.1)',
    primary: '#007bff',
    coloredText: '#2B4FA7',
    openButtonBackground: '#4C6EF5',
    disabledButton: '#A0AEC0', // Disabled button color for light mode
  },
  dark: {
    text: '#FFFFFF',
    textPrimary: '#FFFFFF',
    textSecondary: '#CBD5E0',
    background: '#1A202C',
    backgroundSecondary: '#131E24',
    tint: tintColorDark,
    icon: '#CBD5E0',
    tabIconDefault: '#A0AEC0',
    tabIconSelected: tintColorDark,
    buttonText: '#FFFFFF',
    framButtonText: '#FFFFFF',
    buttonBackground: '#2D3748',
    buttonSecondary: '#4A5568',
    inactiveButtonColor: '#4A5568',
    inputBackground: '#2D3748',
    inputText: '#FFFFFF',
    messageBackground: '#2D3748',
    messageText: '#FFFFFF',
    messageTimestamp: '#A0AEC0',
    notificationBackground: '#4A5568',
    notificationText: '#FFFFFF',
    transparent: 'rgba(0, 0, 0, 0.5)',
    primary: '#1a73e8',
    coloredText: '#1a73e8',
    openButtonBackground: '#2C5282',
    disabledButton: '#4A5568', // Disabled button color for dark mode
  },
};
